ingestion_program/systematics.py

There were 2 values wrong in the postprocess of  systematics module,  
Regards 
Ragansu

systematics bugg fixed

---

ingestion_program/ingestion.py
ingestion_program/ingestion_parallel.py

There was a error in ingestion which comes to play when multiple mu is used. this was due to hard coding number of mus in the past. 
Regards 
Ragansu

Ingestion change

---

ingestion_program/ingestion_parallel.py

The parallelization is performed using a process pool and shared memory to hold the test data.

Parallelize testing

---

ingestion_program/ingestion.py
ingestion_program/ingestion_parallel.py

Changed read dtype of test set to float 32 in pd.read_csv in both ingestion and ingestion parallel

change read dtype to float 32

---

ingestion_program/ingestion_parallel.py

To make it json serializable we had to add to_list()
RC

fixed issue with json

---

scripts/Public_data_generator.py

This code takes location of full train data as input and splits it into 4 parts public_train, public_test, sample_train and  sample_test
sample set is 1% of public set
RC

Public data generator

---

ingestion_program/ingestion.py
ingestion_program/ingestion_parallel.py
scoring_program/score.py

I added a small function to  save ingestion time and use it in scoring... this way we can add it to the leader board if I am not wrong. @ihsaan-ullah  Please comment.
RC

Ingestion time

---

ingestion_program/ingestion.py
ingestion_program/ingestion_parallel.py
scoring_program/score.py

So The leader board need to have score as int or float so text is not as option, I changed the format of duration. 
RC

Durarion min

---

pages/starting_kit.md

updated 1 line in page to contain link to playground competition
RC

updated 1 line in page

---

sample_code_submission/model.py

updated the model to have run on saved model if available
RC

updated model to combine train and run saved model

---

ingestion_program/ingestion_parallel.py

This is current draftly, need to test when PM is back.

Round robin over available devices

---

pages/evaluation.md

updating evaluation page

---

ingestion_program/datasets.py
sample_code_submission/model.py

changed train_test_split to model instead of higgsML package

changed train_test_split to model instead of higgsML package

---

requirements.txt

Requirements file added from #61
@jvdudley you can update the file with versions that works for you and also add missing packages. I let you merge this PR when you are done.

Requirements file added

---

ingestion_program/metadata.yaml

Ingestion command was multiline which was making problems on codabench. Now the command is single line

single line command

---

ingestion_program/datasets.py

bug fix public data

---

docs/pages/data.md
ingestion_program/datasets.py

update Public_data link

---

ingestion_program/systematics.py

There was an issue where the weights of the original set was changing for each pseudo experiment
The issue is fixed by using a temp_data. 
RC

fix - systematics.py : made changes to avoid modifying original test_set

---

ingestion_program/systematics.py
sample_code_submission/boosted_decision_tree.py
sample_code_submission/model.py
sample_code_submission/statistical_analysis.py

The stats-only results have been tested with `1-bin` and `5-bin` cases.

Stat only results fixed

---

sample_code_submission/boosted_decision_tree.py

fix xgboost version error

---

ingestion_program/run_ingestion.py

Added code to make sub directories added to submission_dir
RC

Fix -  Sub directories added to submission_dir

---

README.md
ingestion_program/README.md
sample_code_submission/README.md
scoring_program/README.md
test_model/README.md

Added READMEs to ingestion, scoring , sample submission and test model
Also corrected a typo in README of conda 
RC

Update readmes in the repo.

---

ingestion_program/systematics.py

All changes in systematics.py
Fix #105  
Fix #106

Fix #105 (do not remove event based on jet subleading pt) and #106 (.ipynb was not running on Mac)

---

docs/pages/data.md

I rearranged the tables for clarity
RC

updated data page table

---

ingestion_program/systematics.py

fix systematics bug

---

docs/pages/data.md

changed luminosity from  36 to 10 fb-1
RC

changed luminosity

---

StartingKit_HiggsML_Uncertainty_Challenge.ipynb

public data message added to warn users not to download public data twice

starting kit public data

---

.gitignore
ingestion_program/datasets.py
ingestion_program/ingestion_parallel.py
ingestion_program/run_ingestion.py
ingestion_program/systematics.py
scoring_program/run_scoring.py
scoring_program/score.py

I changed many prints to logger to run the system in info mode for competition and debug mode for internal testing 
RC

Updated prints to logging

---

ingestion_program/ingestion.py

There was a mistake in PR : https://github.com/FAIR-Universe/HEP-Challenge/pull/127
I forgot to push ingestion.py to the branch
here is the fix
RC

patch for ingestion

---

ingestion_program/datasets.py
ingestion_program/derived_quantities.py
ingestion_program/ingestion.py
ingestion_program/ingestion_parallel.py
scoring_program/score.py

This is a PR to fix the issue https://github.com/FAIR-Universe/HEP-Challenge/issues/126 of single precision
Also tweeked the logger for easier debugging.

fixed double point issue + logs

---

conda/requirements.txt

Minor fix for requirements

---

ingestion_program/ingestion.py

removed del self.data for making reruning starting easier
RC

removed del self.data for making reruning starting easier

---

pages/terms.md

We should update the terms page with these changes on codabnech when merging their PR

terms page updated to mention pseudo experiments

---

pages/data.md

The change was made in `pages/data.md`

Added (6.5 GB) to the data download link (requested by Wahid)

---

pages/terms.md

**Todo for me:** update codabench page after merging this.

affiliation terms updated

---

pages/evaluation.md

I added a summary of the submission requirements and the hardware being used.

update evalution page

---

scoring_program/score.py

updated score to give warning for negative interval.
and removed those intervals from the coverage plot.
RC

fix: updated score to give warning for negative interval.

---

scoring_output/scores.json
scoring_program/score.py

The Order of the results being pulled were not correct, we added a sorting step to fix this 
RC

updated Scoring file order

---

pages/Front_page.md

Updated tutorial info and organizer name on Codabench

Updated tutorial info and organizer name on Codabench

---

conda/README.md

- updated python version to 3.12.8 to match with the pipeline test python version
- installed fresh packages in the new conda env, everything went well

Conda env python version updated to 3.12.8

---

ingestion_program/datasets.py

In `load_train_set()`  the `selected_indices`  which the users can provide needs to sorted else it will couse issues. So instead I added a sort inside function for safety. 
Thanks
Ragansu

updated the issue with unsorted indexes.
